apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  mysql-host: YndpY29yZzFsY214YzR4cG9vanYtbXlzcWwuc2VydmljZXMuY2xldmVyLWNsb3VkLmNvbQ==
  mysql-port: MzMwNg==
  mysql-database: YndpY29yZzFsY214YzR4cG9vanY=
  mysql-user: dWpwOXhjaTNqd2Y4a3hsOA==
  mysql-password: cE01MVUwZHpEUXpvaUJQNEtudUg=

